# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site Info
title: test #Awesome Kenta
description: # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kentaccn.com/" # the base hostname & protocol for your site, e.g. http://example.com
charset: utf-8
logo: '/public/logo.png'

# Site configurations
show_dir_listing: false
allpost: "all"
port:    4000
gems: [jekyll-feed, emoji_for_jekyll, jekyll-paginate, jekyll-paginate-categories, jekyll-paginate-tags]
markdown: kramdown
kramdown:
  input: GFM
sass:
  style: compressed
  sass_dir: "/assets/_sass"
images: "assets/images"

##for fixed page, not post
pages: "_pages"
exclude:
  - Gemfile
  - Gemfile.lock
  - gitignore

version: 1.0.0
emoji-images-path: "images/emoji"
include: ["_pages"]


paginate: 1
paginate_path: "/all/page/:num"

paginate_category_basepath: '/:name'
paginate_category_layout: 'categories.html'

paginate_tag_path: '/page/:num'
paginate_tag_basepath: '/:name'
paginate_tag_layout: 'tags.html'

permalink: /:title

# About/contact
author:
  name: Kenta
  description: An INTJ multipotentialite <strong>developer, designer and researcher</strong>, going to change the world.
  gravatar:  # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/kentaccn
    github:    https://github.com/kentaccn
    # facebook:  <hide>
    twitter:   https://twitter.com/kentaccn
    weibo:     <hide>
    email:     http://www.google.com/recaptcha/mailhide/d?k=01QwcSlrS_xqOdmeyWX8ct0g==&c=8R6cX9FVhf0yZl32JHmZTKokHpGW98hWgrBrS3_57jU=

# Navigation (2nd level links supported)
#nav:
  #Home:           
  #  - '/'
  #cat:
  #cats: 
    # - '/cats/'
  #tags: 
    # - '/tags/' 
  #Design:           
  #  - '/design/'
  #  - { Categories: '/cats/' }
  #  - { Tags: '/tags/' }
  #About:          
  #  - '/about/'
  #Contact:
  #  - /contact
  #Github Project: 
  #  - 'http://codinfox.github.io/'

# Where are tags and categories displayed
#tag_page: '/tags/'
#category_page: '/cats/'


# Posts settings
future: true
safe: true
lsi: false

#excerpt_separator: "\n\n"
excerpt_separator: "<!-- more -->"
emoji: false
emoji-whitelist:
  - bowtie
emoji-blacklist:
  #- smile


bruce:
  image: public/bruce_likes_lego_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/Bruce-Likes-Lego-320214734">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
#disqus_short_name:  # leave blank if you don't want disqu




