# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site Info
title: test #Awesome Kenta
description: # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
charset: utf-8

# Site configurations
show_dir_listing: false
port:    4000
gems: [jekyll-feed, emoji_for_jekyll, jekyll-paginate, jekyll-paginate-categories, jekyll-paginate-tags]
markdown: kramdown
kramdown:
  input: GFM
sass:
  style: compressed
  sass_dir: "assets/_sass"
images: "/assets/images"

##for fixed page, not post
pages: "/_pages"
exclude:
  - Gemfile
  - Gemfile.lock
  - gitignore

paginate: 1
paginate_path: "/all/page/:num"

version: 1.0.0
emoji-images-path: "img/emoji"
include: ["_pages"]
#category_dir: "./_pages/cat"
#category_layout: "index.html"
#tag_dir: "./_pages/tag"
#tag_layout: "index.html"

#paginate_per_category: true
#default_category: "."
paginate_category_basepath: '/:name/'
paginate_category_layout: 'categories.html'

paginate_tag_basepath: '/:name/'
paginate_tag_layout: 'tags.html'

permalink: pretty

# About/contact
author:
  name: Kenta
  description: A passionate <strong>developer and researcher</strong>, learning to be a giant.
  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/codinfox
    # facebook:  <hide>
    twitter:   https://twitter.com/Li_Zhihao
    weibo:     http://weibo.com/41173780
    email:     http://www.google.com/recaptcha/mailhide/d?k=01QwcSlrS_xqOdmeyWX8ct0g==&c=8R6cX9FVhf0yZl32JHmZTKokHpGW98hWgrBrS3_57jU=

# Navigation (2nd level links supported)
#nav:
  #Home:           
  #  - '/'
  #cat:
  #cats: 
    # - '/cats/'
  #tags: 
    # - '/tags/' 
  #Design:           
  #  - '/design/'
  #  - { Categories: '/cats/' }
  #  - { Tags: '/tags/' }
  #About:          
  #  - '/about/'
  #Contact:
  #  - /contact
  #Github Project: 
  #  - 'http://codinfox.github.io/'

# Where are tags and categories displayed
#tag_page: '/tags/'
#category_page: '/cats/'


# Posts settings
future: true
safe: true
lsi: false

excerpt_separator: "\n\n"
excerpt_separator: "<!-- more -->"
emoji: false
emoji-whitelist:
  - bowtie
emoji-blacklist:
  - smile


hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name:  # leave blank if you don't want disqu




